# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2004"
    config.vm.provider "virtualbox" do |vb|

    vb.name = "NoviNano"

    vb.memory = "2024"

    vb.cpus = 2
	end
	
	  config.vm.hostname = "NoviNano"



  config.vm.network "public_network", ip: "192.168.88.55"

 
end